name: "Train-Model"

on:
  push:
  
jobs:
  train-model:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python"
        run: |
          apt-get update -y
          pip install --upgrade pip
      - name: "Install dependencies"
        run: |
          pip install -r requirements.txt
      - name: "Train Model"
        run: |
          python main.py
      - name: "Upload evaluation report"
        uses: actions/upload-artifact@v2
        with:
          name: evaluation_report
          path: evaluation_report.txt

  generate-comment:
    needs: train-model
    runs-on: ubuntu-latest
    steps:
      - name: "Download evaluation report"
        uses: actions/download-artifact@v2
        with:
          name: evaluation_report
      - name: "Setup CML"
        uses: iterative/setup-cml@v1
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: "Send CML Report"
        run: |
          cat evaluation_report.txt >> report.md
          cml comment create --pr --publish report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
