name: "Train-Model"

on:
  push:

jobs:
  train-model:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python"
        run: |
          apt-get update -y
          apt install graphviz -y
          pip install --upgrade pip
      - name: "Install dependencies"
        run: |
          pip install -r requirements.txt
      - name: "Train Model"
        run: |
          python main.py --train
      - name: "Upload evaluation report"
        uses: actions/upload-artifact@v2
        with:
          name: evaluation_report_main
          path: outputs
      - name: "Upload model"
        uses: actions/upload-artifact@v2
        with:
          name: model_main
          path: models
  test-model:
    needs: train-model
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python"
        run: |
          apt-get update -y
          apt install graphviz -y
          pip install --upgrade pip
      - name: "Install dependencies"
        run: |
          pip install -r requirements.txt
      - name: "Download Model"
        uses: actions/download-artifact@v2
        with:
          name: model_main
      - name: "Test Model"
        run: |
          python main.py --test
      - name: "Upload evaluation report"
        uses: actions/upload-artifact@v2
        with:
          name: test_report_main
          path: outputs
  generate-comment:
    needs: test-model
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Download evaluation report"
        uses: actions/download-artifact@v2
        with:
          name: evaluation_report_main
      - name: "Download test report"
        uses: actions/download-artifact@v2
        with:
          name: test_report_main
      - name: "Send CML Report"
        run: |
          echo "## Model Report" > report.md
          echo "### Validation Metrics" >> report.md
          cat evaluation_report_validation.txt >> report.md
          echo "\n" >> report.md
          echo "### Testing Metrics" >> report.md
          cat evaluation_report_test.txt >> report.md
          echo "\n" >> report.md
          echo "## Model Visualization" >> report.md
          echo "### Model Architecture" >> report.md
          echo "![](./model_architecture.png)" >> report.md
          echo "### Accuracy Plot" >> report.md
          echo "![](./accuracy_plot.png)" >> report.md
          echo "### Loss Plot" >> report.md
          echo "![](./loss_plot.png)" >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
