name: "Train-Model"

on:
  push:

jobs:
  train-model:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - name: "Set up Python"
        run: |
          apt-get update -y
          apt install graphviz -y
          pip install --upgrade pip
      - name: "Install dependencies"
        run: |
          pip install -r requirements.txt
      - name: "Train Model"
        run: |
          python main.py
      - name: "Send CML Report"
        run: |
          echo "## Model Report" > report.md
          cat evaluation_report.txt >> report.md
          echo "## Model Visualization" >> report.md
          echo "### Model Architecture" >> report.md
          echo "![](outputs/model_architecture.png)" >> report.md
          echo "### Accuracy Plot" >> report.md
          echo "![](outputs/accuracy_plot.png)" >> report.md
          echo "### Loss Plot" >> report.md
          echo "![](outputs/loss_plot.png)" >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
